INSERT INTO states(estado, capital, población) VALUES('AGUASCALIENTES', 'AGUASCALIENTES', '1,425,607');
INSERT INTO states(estado, capital, población) VALUES('BAJA CALIFORNIA ', 'MEXICALI', '3,769,020');
INSERT INTO states(estado, capital, población) VALUES('BAJA CALIFORNIA SUR', 'LA PAZ', '798,447');
INSERT INTO states(estado, capital, población) VALUES('CAMPECHE', 'CAMPECHE', '928,363');
INSERT INTO states(estado, capital, población) VALUES('CHIAPAS', 'TUXTLA GUTIÉRREZ', '5,543,828');
INSERT INTO states(estado, capital, población) VALUES('CHIHUAHUA', 'CHIHUAHUA', '3,741,869');
INSERT INTO states(estado, capital, población) VALUES('CIUDAD DE MÉXICO', 'CIUDAD DE MÉXICO', '9,209,944');
INSERT INTO states(estado, capital, población) VALUES('COAHUILA DE ZARAGOZA', 'SALTILLO', '3,146,771');
INSERT INTO states(estado, capital, población) VALUES('COLIMA', 'COLIMA', '731,391');
INSERT INTO states(estado, capital, población) VALUES('DURANGO', 'VICTORIA DE DURANGO', '1,832,650');
INSERT INTO states(estado, capital, población) VALUES('ESTADO DE MÉXICO', 'TOLUCA DE LERDO', '16,992,418');
INSERT INTO states(estado, capital, población) VALUES('GUANAJUATO', 'GUANAJUATO', '6,166,934');
INSERT INTO states(estado, capital, población) VALUES('GUERRERO', 'CHILPANCINGO DE BRAVO', '3,540,685');
INSERT INTO states(estado, capital, población) VALUES('HIDALGO', 'PACHUCA DE SOTO', '3,082,841');
INSERT INTO states(estado, capital, población) VALUES('JALISCO', 'GUADALAJARA', '8,348,151');
INSERT INTO states(estado, capital, población) VALUES('MICHOACAN DE OCAMPO', 'MORELIA', '4,748,846');
INSERT INTO states(estado, capital, población) VALUES('MORELOS', 'CUERNAVACA', '1,971,520');
INSERT INTO states(estado, capital, población) VALUES('NAYARIT', 'TEPIC', '1,235,456');
INSERT INTO states(estado, capital, población) VALUES('NUEVO LEÓN', 'MONTERREY', '5,784,442');
INSERT INTO states(estado, capital, población) VALUES('OAXACA', 'OAXACA DE JUÁREZ', '4,132,148');
INSERT INTO states(estado, capital, población) VALUES('PUEBLA', 'PUEBLA DE ZARAGOZA', '6,583,278');
INSERT INTO states(estado, capital, población) VALUES('QUERÉTARO', 'SANTIAGO DE QUERÉTARO', '2,368,467');
INSERT INTO states(estado, capital, población) VALUES('QUINTANA ROO', 'CHETUMAL', '1,857,985');
INSERT INTO states(estado, capital, población) VALUES('SAN LUIS POTOSÍ', 'SAN LUIS POTOSÍ', '2,822,255');
INSERT INTO states(estado, capital, población) VALUES('SINALOA', 'CULIACÁN ROSALES', '3,026,943');
INSERT INTO states(estado, capital, población) VALUES('SONORA', 'HERMOSILLO', '2,944,840');
INSERT INTO states(estado, capital, población) VALUES('TABASCO', 'VILLAHERMOSA', '2,402,598');
INSERT INTO states(estado, capital, población) VALUES('TAMAULIPAS', 'CIUDAD VICTORIA', '3,527,735');
INSERT INTO states(estado, capital, población) VALUES('TLAXCALA', 'TLAXCALA DE XICOHTÉNCATL', '1,342,977');
INSERT INTO states(estado, capital, población) VALUES('VERACRUZ DE IGNACIO DE  LA LLAVE', 'XALAPA-ENRIQUEZ', '8,062,579');
INSERT INTO states(estado, capital, población) VALUES('YUCATÁN', 'MERIDA', '2,320,898');
INSERT INTO states(estado, capital, población) VALUES('ZACATECAS', 'ZACATECAS', '1,622,138');
